// console.log(newValue);
// var newValue = 200;
const name = "Dndev";
const major = "graphic designer!";
console.log(name);
console.log(typeof name);
const newString = "My name is " + name + " and i'm a " + major;
console.log(newString);
const newStr2 = `My name is Duong Nguyen and i'm a frontend developer`;
console.log(newStr2);
