// console.log(newValue);
// var newValue = 200;
const name = "Dngdev";
const major = "UI UX designer!";
console.log(name);
console.log(typeof name);
const newString = "My name is " + name + " and i'm a " + major;
console.log(newString);
const newStr2 = `My name is ${name} and i'm a ${major}`;
const lengthOfStr = "my name is Duong Nguyen";
console.log(newStr2);
console.log(lengthOfStr.length);
const demoStr = "Frontend Developer    ";
console.log(demoStr.split(""));
console.log(demoStr.split(" "));
console.log(demoStr.toUpperCase(""));
console.log(demoStr.includes("Frontend"));
console.log(demoStr.startsWith("Fr"));
console.log(demoStr.lastIndexOf("e"));
console.log(demoStr.indexOf("e"));
console.log(demoStr.replace("Frontend", "UiUx"));
console.log(demoStr.slice(0, 8));
console.log(demoStr.slice(0, 8));
console.log(demoStr.slice(-9));
console.log(demoStr.trimStart());
console.log(demoStr.charAt(2));
console.log(demoStr.subStr());
