// 1.string in javascript;
// console.log(newValue);
// var newValue = 200;
// const name = "Dngdev";
// const major = "UI UX designer!";
// console.log(name);
// console.log(typeof name);
// const newString = "My name is " + name + " and i'm a " + major;
// console.log(newString);
// const newStr2 = `My name is ${name} and i'm a ${major}`;
// const lengthOfStr = "my name is Duong Nguyen";
// console.log(newStr2);
// console.log(lengthOfStr.length);
// const demoStr = "Frontend Developer    ";
// console.log(demoStr.split(""));
// console.log(demoStr.split(" "));
// console.log(demoStr.toUpperCase(""));
// console.log(demoStr.includes("Frontend"));
// console.log(demoStr.startsWith("Fr"));
// console.log(demoStr.lastIndexOf("e"));
// console.log(demoStr.indexOf("e"));
// console.log(demoStr.replace("Frontend", "UiUx"));
// console.log(demoStr.slice(0, 8));
// console.log(demoStr.slice(0, 8));
// console.log(demoStr.slice(-9));
// console.log(demoStr.trimStart());
// console.log(demoStr.charAt(2));
// console.log(demoStr.substring(1, 5));
// console.log(
//   demoStr
//     .trim()
//     .replace("Developer", "Developer and Designer Is me")
//     .toUpperCase()
// );
// 2.Number in javasscript;
// const number1 = "5";
// const number2 = "5.3";
// console.log(parseInt(number2));
// console.log(parseFloat(number2));
// const number3 = "-100";
// console.log(Math.abs(number3));
// console.log(Math.round(number2));
// console.log(parseFloat((1 / 3).toFixed(2)));
// console.log(Math.ceil(Math.random() * 10));
// console.log(`Max: ${Math.max(3, 4, 7)}`);
// console.log(Math.pow(10, 10));
// console.log(isNaN("this is a string"));
// console.log(isNaN("474958495"));
// console.log(Number.isNaN(NaN));
console.log(Number("4.5"));
console.log(Number("asjdhf"));
console.log(Number(undefined));
console.log(Number(null));
console.log(Number(false));
console.log(Number(true));
console.log(String("this is me"));
console.log(`Boolean of : ${Boolean(0)}`);
console.log(`Boolean of : ${Boolean("")}`);
console.log(`Boolean of : ${Boolean(undefined)}`);
console.log(`Boolean of : ${Boolean(false)}`);
console.log(`Boolean of : ${Boolean("Me")}`);
